# Generated by Django 4.2.5 on 2024-12-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя персонажа')),
                ('player_name', models.CharField(blank=True, max_length=100, verbose_name='Имя игрока')),
                ('character_class', models.CharField(blank=True, max_length=50, verbose_name='Класс')),
                ('race', models.CharField(max_length=50, verbose_name='Раса')),
                ('background', models.TextField(blank=True, null=True, verbose_name='Предыстория')),
                ('alignment', models.CharField(blank=True, max_length=20, verbose_name='Мировоззрение')),
                ('experience', models.IntegerField(blank=True, default=0, verbose_name='Опыт')),
                ('level', models.IntegerField(blank=True, default=1, verbose_name='Уровень')),
                ('notes', models.CharField(blank=True, max_length=999, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'db_table': 'Информация о персонаже',
            },
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='Сила')),
                ('dexterity', models.IntegerField(blank=True, null=True, verbose_name='Ловкость')),
                ('constitution', models.IntegerField(blank=True, null=True, verbose_name='Телосложение')),
                ('intelligence', models.IntegerField(blank=True, null=True, verbose_name='Интеллект')),
                ('wisdom', models.IntegerField(blank=True, null=True, verbose_name='Мудрость')),
                ('charisma', models.IntegerField(blank=True, null=True, verbose_name='Харизма')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'db_table': 'Характерисики',
            },
        ),
        migrations.CreateModel(
            name='Other_characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspiration', models.BooleanField(blank=True, default=False, verbose_name='Вдохновение')),
                ('proficiency_bonus', models.IntegerField(blank=True, default=2, verbose_name='Бонус владения')),
                ('armor_class', models.IntegerField(blank=True, default=10, verbose_name='КЗ')),
                ('initiative', models.IntegerField(blank=True, default=0, verbose_name='Инициатива')),
                ('speed', models.IntegerField(blank=True, default=30, verbose_name='Скорость')),
                ('current_hp', models.IntegerField(blank=True, default=0, verbose_name='Текущие хиты')),
                ('temporary_hp', models.IntegerField(blank=True, default=0, null=True, verbose_name='Временные хиты')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'db_table': 'Другие характеристики',
            },
        ),
        migrations.CreateModel(
            name='Saving_throws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_strength', models.BooleanField(blank=True, default=False, null=True, verbose_name='Сп_сила')),
                ('st_dexterity', models.BooleanField(blank=True, default=False, null=True, verbose_name='Сп_ловкость')),
                ('st_constitution', models.BooleanField(blank=True, default=False, null=True, verbose_name='Сп_телосложение')),
                ('st_intelligence', models.BooleanField(blank=True, default=False, null=True, verbose_name='Сп_интеллект')),
                ('st_wisdom', models.BooleanField(blank=True, default=False, null=True, verbose_name='Сп_мудрость')),
                ('st_charisma', models.BooleanField(blank=True, default=False, null=True, verbose_name='Сп_харизма')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'db_table': 'Спасброски',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acrobatics', models.BooleanField(blank=True, default=False, verbose_name='Акробатика (Лов)')),
                ('analysis', models.BooleanField(blank=True, default=False, verbose_name='Анализ (Инт)')),
                ('athletics', models.BooleanField(blank=True, default=False, verbose_name='Атлетика (Сил)')),
                ('perception', models.BooleanField(blank=True, default=False, verbose_name='Восприятие (Муд)')),
                ('survival', models.BooleanField(blank=True, default=False, verbose_name='Выживание (Муд)')),
                ('performance', models.BooleanField(blank=True, default=False, verbose_name='Выступление (Хар)')),
                ('intimidation', models.BooleanField(blank=True, default=False, verbose_name='Запугивание (Хар)')),
                ('history', models.BooleanField(blank=True, default=False, verbose_name='История (Инт)')),
                ('sleight_of_hand', models.BooleanField(blank=True, default=False, verbose_name='Ловкость рук (Лов)')),
                ('magic', models.BooleanField(blank=True, default=False, verbose_name='Магия (Инт)')),
                ('medicine', models.BooleanField(blank=True, default=False, verbose_name='Медицина (Муд)')),
                ('deception', models.BooleanField(blank=True, default=False, verbose_name='Обман (Хар)')),
                ('nature', models.BooleanField(blank=True, default=False, verbose_name='Природа (Инт)')),
                ('insight', models.BooleanField(blank=True, default=False, verbose_name='Проницательность (Муд)')),
                ('religion', models.BooleanField(blank=True, default=False, verbose_name='Религия (Инт)')),
                ('stealth', models.BooleanField(blank=True, default=False, verbose_name='Скрытность (Лов)')),
                ('persuasion', models.BooleanField(blank=True, default=False, verbose_name='Убеждение (Хар)')),
                ('animal_handling', models.BooleanField(blank=True, default=False, verbose_name='Уход за животными (Муд)')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'db_table': 'Навыки',
            },
        ),
    ]
