# Generated by Django 4.2.5 on 2025-01-22 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(blank=True, default=10, verbose_name='Сила')),
                ('dexterity', models.IntegerField(blank=True, default=10, verbose_name='Ловкость')),
                ('constitution', models.IntegerField(blank=True, default=10, verbose_name='Телосложение')),
                ('intelligence', models.IntegerField(blank=True, default=10, verbose_name='Интеллект')),
                ('wisdom', models.IntegerField(blank=True, default=10, verbose_name='Мудрость')),
                ('charisma', models.IntegerField(blank=True, default=10, verbose_name='Харизма')),
                ('st_strength', models.IntegerField(blank=True, default=1, verbose_name='Сп_сила')),
                ('st_dexterity', models.IntegerField(blank=True, default=1, verbose_name='Сп_ловкость')),
                ('st_constitution', models.IntegerField(blank=True, default=1, verbose_name='Сп_телосложение')),
                ('st_intelligence', models.IntegerField(blank=True, default=1, verbose_name='Сп_интеллект')),
                ('st_wisdom', models.IntegerField(blank=True, default=1, verbose_name='Сп_мудрость')),
                ('st_charisma', models.IntegerField(blank=True, default=1, verbose_name='Сп_харизма')),
                ('acrobatics', models.IntegerField(blank=True, default=1, verbose_name='Акробатика (Лов)')),
                ('analysis', models.IntegerField(blank=True, default=1, verbose_name='Анализ (Инт)')),
                ('athletics', models.IntegerField(blank=True, default=1, verbose_name='Атлетика (Сил)')),
                ('perception', models.IntegerField(blank=True, default=1, verbose_name='Восприятие (Муд)')),
                ('survival', models.IntegerField(blank=True, default=1, verbose_name='Выживание (Муд)')),
                ('performance', models.IntegerField(blank=True, default=1, verbose_name='Выступление (Хар)')),
                ('intimidation', models.IntegerField(blank=True, default=1, verbose_name='Запугивание (Хар)')),
                ('history', models.IntegerField(blank=True, default=1, verbose_name='История (Инт)')),
                ('sleight_of_hand', models.IntegerField(blank=True, default=1, verbose_name='Ловкость рук (Лов)')),
                ('magic', models.IntegerField(blank=True, default=1, verbose_name='Магия (Инт)')),
                ('medicine', models.IntegerField(blank=True, default=1, verbose_name='Медицина (Муд)')),
                ('deception', models.IntegerField(blank=True, default=1, verbose_name='Обман (Хар)')),
                ('nature', models.IntegerField(blank=True, default=1, verbose_name='Природа (Инт)')),
                ('insight', models.IntegerField(blank=True, default=1, verbose_name='Проницательность (Муд)')),
                ('religion', models.IntegerField(blank=True, default=1, verbose_name='Религия (Инт)')),
                ('stealth', models.IntegerField(blank=True, default=1, verbose_name='Скрытность (Лов)')),
                ('persuasion', models.IntegerField(blank=True, default=1, verbose_name='Убеждение (Хар)')),
                ('animal_handling', models.IntegerField(blank=True, default=1, verbose_name='Уход за животными (Муд)')),
                ('inspiration', models.BooleanField(default=False, verbose_name='Вдохновение')),
                ('armor_class', models.IntegerField(default=10, verbose_name='КЗ')),
                ('speed', models.IntegerField(default=30, verbose_name='Скорость')),
                ('current_hp', models.IntegerField(blank=True, null=True, verbose_name='Текущие хиты')),
                ('max_hp', models.IntegerField(blank=True, null=True, verbose_name='Максимальные хиты')),
                ('temporary_hp', models.IntegerField(blank=True, null=True, verbose_name='Временные хиты')),
                ('success1', models.BooleanField(default=False, verbose_name='Успех 1')),
                ('success2', models.BooleanField(default=False, verbose_name='Успех 2')),
                ('success3', models.BooleanField(default=False, verbose_name='Успех 3')),
                ('failure1', models.BooleanField(default=False, verbose_name='Провал 1')),
                ('failure2', models.BooleanField(default=False, verbose_name='Провал 2')),
                ('failure3', models.BooleanField(default=False, verbose_name='Провал 3')),
                ('bone_of_hit', models.CharField(blank=True, max_length=10, verbose_name='Кость хитов')),
                ('total_bone_of_hit', models.CharField(blank=True, max_length=10, verbose_name='Всего кость хитов')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя персонажа')),
                ('player_name', models.CharField(blank=True, max_length=100, verbose_name='Имя игрока')),
                ('character_class', models.CharField(blank=True, max_length=50, verbose_name='Класс')),
                ('race', models.CharField(blank=True, max_length=50, verbose_name='Раса')),
                ('background', models.TextField(blank=True, null=True, verbose_name='Предыстория')),
                ('alignment', models.CharField(blank=True, max_length=20, verbose_name='Мировоззрение')),
                ('experience', models.IntegerField(blank=True, default=0, null=True, verbose_name='Опыт')),
                ('level', models.IntegerField(blank=True, default=1, null=True, verbose_name='Уровень')),
                ('character_traits', models.TextField(blank=True, verbose_name='Черты характера')),
                ('ideals', models.TextField(blank=True, verbose_name='Идеалы')),
                ('attachments', models.TextField(blank=True, verbose_name='Привязанности')),
                ('weaknesses', models.TextField(blank=True, verbose_name='Слабости')),
                ('skills_and_abilities', models.TextField(blank=True, verbose_name='Умения и способности')),
                ('equipment', models.TextField(blank=True, verbose_name='Снаряжение')),
                ('other_proficiencies', models.TextField(blank=True, verbose_name='Прочие владения и языки')),
                ('attacks_and_spells', models.TextField(blank=True, verbose_name='Атаки и заклинания')),
                ('copper_coins', models.IntegerField(blank=True, null=True, verbose_name='Медные монеты')),
                ('silver_coins', models.IntegerField(blank=True, null=True, verbose_name='Серебряные монеты')),
                ('gold_coins', models.IntegerField(blank=True, null=True, verbose_name='Золотые монеты')),
                ('electrum_coins', models.IntegerField(blank=True, null=True, verbose_name='Электрумовые монеты')),
                ('platinum_coins', models.IntegerField(blank=True, null=True, verbose_name='Платиновые монеты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'db_table': 'characteristics',
            },
        ),
    ]
